/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_davidwei_perfmock_internal_perf_network_JavaTense */

#ifndef _Included_uk_davidwei_perfmock_internal_perf_network_JavaTense
#define _Included_uk_davidwei_perfmock_internal_perf_network_JavaTense
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_init
  (JNIEnv *, jclass);

/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_destroy
  (JNIEnv *, jclass);

/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    time
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_time
  (JNIEnv *, jclass);

/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    scale
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_scale
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    reset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_reset
  (JNIEnv *, jclass);

/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    sleep0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_sleep0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_davidwei_perfmock_internal_perf_network_JavaTense
 * Method:    jump0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_davidwei_perfmock_internal_perf_network_JavaTense_jump0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
